version: '3.1'

services:
  postgress-ktapi-base:
    image: "postgres"
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: local
      POSTGRES_DB: app